export const themeColors = {
  light: {    
    primaryColor: "#2F19B7",
    primaryLightColor: "#2f19b799",
    secondaryColor: "#5733FF",
    alertColor: "#B31911",    
    grayColor: "#dddddd",
    lightGrayColor: "#cccccc",
    textColor: "#1a1a1a",    
    boxBackgroundColor: "#ffffff",
    validColor: "##008000",
    invalidColor: "#B00020",
  },
  dark: {    
    primaryColor: "#9E84FF",
    primaryLightColor: "#9e84ff99", 
    secondaryColor: "#C0ADFF",
    alertColor: "#FB8558",
    grayColor: "#dddddd99",
    lightGrayColor: "eeeeee99",
    textColor: "#ffffff",    
    boxBackgroundColor: "#121212",
    validColor: "#ccffcc",
    invalidColor: "#eeeeee",
  },
};
